-- MySQL Script generated by MySQL Workbench
-- Wed Apr  8 00:39:16 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ventas_ci
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ventas_ci
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ventas_ci` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `ventas_ci` ;

-- -----------------------------------------------------
-- Table `ventas_ci`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas_ci`.`categorias` (
  `idcategorias` INT NOT NULL,
  `nombre` VARCHAR(100) NULL,
  `descripcion` VARCHAR(100) NULL,
  `fecha_update` TIMESTAMP NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`idcategorias`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventas_ci`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas_ci`.`productos` (
  `idproductos` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `descripcion` VARCHAR(100) NULL,
  `precio` VARCHAR(45) NULL,
  `stock` VARCHAR(45) NULL,
  `id_categoria` INT NULL,
  `fecha_update` TIMESTAMP NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`idproductos`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) ,
  INDEX `fk_categoria_producto_idx` (`id_categoria` ASC) ,
  CONSTRAINT `fk_categoria_producto`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `ventas_ci`.`categorias` (`idcategorias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventas_ci`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas_ci`.`clientes` (
  `idclientes` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(100) NULL,
  `apellidos` VARCHAR(100) NULL,
  `telefono` CHAR(9) NULL,
  `direccion` VARCHAR(100) NULL,
  `ruc` CHAR(11) NULL,
  `empresa` VARCHAR(100) NULL,
  `fecha_update` TIMESTAMP NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`idclientes`),
  UNIQUE INDEX `ruc_UNIQUE` (`ruc` ASC) ,
  UNIQUE INDEX `empresa_UNIQUE` (`empresa` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventas_ci`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas_ci`.`roles` (
  `idroles` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `descripcion` VARCHAR(100) NULL,
  `fecha_update` TIMESTAMP NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`idroles`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventas_ci`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas_ci`.`usuarios` (
  `idusuarios` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(100) NULL,
  `apellidos` VARCHAR(100) NULL,
  `telefono` CHAR(9) NULL,
  `email` VARCHAR(45) NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(100) NULL,
  `id_rol` INT NULL,
  `fecha_update` TIMESTAMP NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`idusuarios`),
  INDEX `fk_rol_usuarios_idx` (`id_rol` ASC) ,
  CONSTRAINT `fk_rol_usuarios`
    FOREIGN KEY (`id_rol`)
    REFERENCES `ventas_ci`.`roles` (`idroles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventas_ci`.`tipo_documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas_ci`.`tipo_documento` (
  `idtipo_documento` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `cantidad` INT NULL,
  `fecha_update` TIMESTAMP NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`idtipo_documento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventas_ci`.`ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas_ci`.`ventas` (
  `idventas` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL,
  `subtotal` VARCHAR(45) NULL,
  `igv` VARCHAR(45) NULL,
  `descuento` VARCHAR(45) NULL,
  `total` VARCHAR(45) NULL,
  `id_tipo_documento` INT NULL,
  `id_cliente` INT NULL,
  `id_usuario` INT NULL,
  `num_documento` VARCHAR(45) NULL,
  `fecha_update` TIMESTAMP NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`idventas`),
  UNIQUE INDEX `num_documento_UNIQUE` (`num_documento` ASC) ,
  INDEX `fk_usuario_venta_idx` (`id_usuario` ASC) ,
  INDEX `fk_cliente_venta_idx` (`id_cliente` ASC) ,
  INDEX `fk_tipo_documento_venta_idx` (`id_tipo_documento` ASC) ,
  CONSTRAINT `fk_usuario_venta`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `ventas_ci`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_venta`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `ventas_ci`.`clientes` (`idclientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tipo_documento_venta`
    FOREIGN KEY (`id_tipo_documento`)
    REFERENCES `ventas_ci`.`tipo_documento` (`idtipo_documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventas_ci`.`detalle_venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas_ci`.`detalle_venta` (
  `iddetalle_venta` INT NOT NULL AUTO_INCREMENT,
  `id_producto` INT NULL,
  `id_venta` INT NULL,
  `precio` VARCHAR(45) NULL,
  `cantidad` VARCHAR(45) NULL,
  `importe` VARCHAR(45) NULL,
  `fecha_update` TIMESTAMP NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`iddetalle_venta`),
  INDEX `fk_venta_detalle_idx` (`id_venta` ASC) ,
  INDEX `fk_prodcuto_detalle_idx` (`id_producto` ASC) ,
  CONSTRAINT `fk_venta_detalle`
    FOREIGN KEY (`id_venta`)
    REFERENCES `ventas_ci`.`ventas` (`idventas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prodcuto_detalle`
    FOREIGN KEY (`id_producto`)
    REFERENCES `ventas_ci`.`productos` (`idproductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
